add method reply_dice and change send_dice docs.
pyrogram/pyrogram pull request #509
Opened 2020-10-04 19:18 UTC by jonatan1609

2020-10-18 15:50 UTC, delivrance requested changes

2020-10-18 15:50 UTC, delivrance commented on pyrogram/methods/messages/send_dice.py
> +                Currently, must be one of :obj:`~pyrogram.emoji.SOCCER_BALL`,  :obj:`~pyrogram.emoji.BASKETBALL`, :obj:`~pyrogram.emoji.DIRECT_HIT` or :obj:`~pyrogram.emoji.GAME_DIE`.
Emoji references don't seem to play nice with docs. We'd better revert to what it was for now.

2020-10-18 23:06 UTC, jonatan1609 commented
I've changed them back

2020-12-11 18:33 UTC, delivrance commented on pyrogram/types/messages_and_media/message.py
> +                file_id, file_ref = None, None
Please revert this, it has nothing to do with dice. You can open a new PR with your proposed changes (the relevant code can now be found in `async def copy`).

2020-12-11 18:34 UTC, delivrance commented on pyrogram/methods/messages/send_dice.py
> +                Currently, must be one of "🎲",  "🎯", "🏀" or "⚽️".	                Emoji on which the dice throw animation is based.
There's also 🎰  now.

2021-01-17 00:55 UTC, closed without merging