Improve typing hints
pyrogram/pyrogram pull request #537
Opened 2020-11-14 14:48 UTC by alissonlauffer

- Change `type1 or type2` to `Union[type1, type2]` because the first one does not work with VSCode/PyCharm (though it does not give any SyntaxError).

2020-11-29 06:09 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_abridged.py
> +    async def recv(self, length: int = 0) -> Union[bytes, None]:
Why don't you use `Optional[bytes]`

2020-11-29 06:16 UTC, KunoiSayami requested changes
Use `Optional[X]` may more intuitive than `Union[X, None]`
Reference: https://docs.python.org/3/library/typing.html#typing.Optional

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/connection.py
> +from typing import Union
```suggestion
from typing import Optional
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/connection.py
> +    async def recv(self) -> Union[bytes, None]:
```suggestion
    async def recv(self) -> Optional[bytes]:
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_abridged.py
> +from typing import Union
```suggestion
from typing import Optional
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_abridged.py
> +    async def recv(self, length: int = 0) -> Union[bytes, None]:
```suggestion
    async def recv(self, length: int = 0) -> Optional[bytes]:
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_abridged_o.py
> +from typing import Union
```suggestion
from typing import Optional
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_abridged_o.py
> +    async def recv(self, length: int = 0) -> Union[bytes, None]:
```suggestion
    async def recv(self, length: int = 0) -> Optional[bytes]:
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_full.py
> +from typing import Union
```suggestion
from typing import Optional
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_full.py
> +    async def recv(self, length: int = 0) -> Union[bytes, None]:
```suggestion
    async def recv(self, length: int = 0) -> Optional[bytes]:
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_intermediate.py
> +from typing import Union
```suggestion
from typing import Optional
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_intermediate.py
> +    async def recv(self, length: int = 0) -> Union[bytes, None]:
```suggestion
    async def recv(self, length: int = 0) -> Optional[bytes]:
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_intermediate_o.py
> +from typing import Union
```suggestion
from typing import Optional
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/connection/transport/tcp/tcp_intermediate_o.py
> +    async def recv(self, length: int = 0) -> Union[bytes, None]:
```suggestion
    async def recv(self, length: int = 0) -> Optional[bytes]:
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/types/messages_and_media/message_entity.py
> +from typing import Union
```suggestion
from typing import Optional
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/types/messages_and_media/message_entity.py
> +    def _parse(client, entity, users: dict) -> Union["MessageEntity", None]:
```suggestion
    def _parse(client, entity, users: dict) -> Optional["MessageEntity"]:
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/types/user_and_chats/user.py
> +from typing import List, Union
```suggestion
from typing import List, Optional
```

2020-11-29 06:16 UTC, KunoiSayami commented on pyrogram/types/user_and_chats/user.py
> +    def _parse(client, user: "raw.types.User") -> Union["User", None]:
```suggestion
    def _parse(client, user: "raw.types.User") -> Optional["User"]:
```

2020-11-29 10:52 UTC, KunoiSayami approved these changes

2020-11-30 02:47 UTC, KunoiSayami approved these changes

2020-12-11 18:24 UTC, delivrance commented on pyrogram/filters.py
> +    def __init__(self, users: Union[int, str, list] = None):
This can be improved with `Union[int, str, List[Union[int, str]]]`

2020-12-11 18:24 UTC, delivrance commented on pyrogram/filters.py
> +    def __init__(self, chats: Union[int, str, list] = None):
Same here, `Union[int, str, List[Union[int, str]]]`

2020-12-20 16:05 UTC, merged